.TH meteoserver Mictronics 1 "05 November 2020" "" ""
.RS
.SH NAME
meteoserver
.SH VERSION
1.0.0
.SH DESCRIPTION
\fBWebsocket server for Vaisalla weather station.
.SH USAGE
\fBmeteoserver [OPTION\.\.\.]
.SH OPTIONS
.TP
.B
\fB-i\fP, \fB--ip\fP=<ip>
Listen IP address or host [default: 127.0.0.1]
.TP
.B
\fB-p\fP, \fB--port\fP=<port>
Listen port [default: 8080]
.TP
.B
\fB--serial\fP=<serial device>
Serial device [default: /dev/ttyUSB0]
.TP
.B
\fB--baudrate\fP=<baudrate>
Serial baudrate [default: 9600]
.TP
.B
\fB--group\fP=<id>
Websocket group id [default: -1]
.TP
.B
\fB--user\fP=<id>
Websocket user id [default: -1]
.TP
.B
\fB-D\fP, \fB--daemon\fP
Run meteoserver as a daemon
.TP
.B
\fB-d\fP, \fB--debug\fP=<level>
Set debug level [default: 0]
.TP
.B
\fB--nogps
Disable GPS support
.SS  HELP OPTIONS
.TP
.B
\fB-?, \fB--help\fP
Give this help list
.TP
.B
\fB--usage\fP
Give a short usage message
.TP
.B
\fB-V\fP, \fB--version\fP
Print program version
.SH BUGS
Report bugs to Michael Wolf <michael@mictronics.de>.
.SH AUTHOR
Michael Wolf
